app/models/Categoria.py
from config import db

class Categoria(db.Model):
    __tablename__="categoria"
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(100))
    descricao = db.Column(db.String(200))

    def __init__(self,nome,descricao):
        self.nome = nome
        self.descricao = descricao

app/models/Fornecedor.py
from config import db

class Fornecedor(db.Model):
    __tablename__ = "fornecedor"
    id = db.Column(db.Integer, primary_key = True)
    nome = db.Column(db.String(100))
    contato = db.Column(db.String(100))
    endereco = db.Column(db.String(200))


    def __init__(self,nome,contato,endereco):
        self.nome = nome
        self.contato = contato
        self.endereco = endereco

app/models/MovimentacaoEstoque.py
from datetime import datetime
from config import db

class MovEstoque(db.Model):
    __tablename__ = "movestoque"

    id = db.Column(db.Integer, primary_key=True)
    id_produto = db.Column(db.Integer, db.ForeignKey('produto.id', ondelete='CASCADE'), nullable=False)
    tipo = db.Column(db.String(50), nullable=False)
    quantidade = db.Column(db.Integer, nullable=False)
    data_hora = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    observacao = db.Column(db.String(200))

    # Relacionamento com Produto
    produto = db.relationship('Produto', back_populates='movestoque')

app/models/Produto.py
from config import db

class Produto(db.Model):
    __tablename__ = "produto"

    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(100), nullable=False)
    descricao = db.Column(db.String(200))
    preco = db.Column(db.Float, nullable=False)
    quantidade_estoque = db.Column(db.Integer, nullable=False)
    id_categoria = db.Column(db.Integer, db.ForeignKey('categoria.id', ondelete='CASCADE'), nullable=False)
    id_fornecedor = db.Column(db.Integer, db.ForeignKey('fornecedor.id', ondelete='CASCADE'), nullable=False)

    # Relacionamentos
    categoria = db.relationship('Categoria', backref='produtos', lazy=True)
    fornecedor = db.relationship('Fornecedor', backref='produtos', lazy=True)
    movestoque = db.relationship('MovEstoque', back_populates='produto', lazy=True, foreign_keys='MovEstoque.id_produto')

    def __init__(self, nome, descricao, preco, quantidade_estoque, id_categoria, id_fornecedor):
        self.nome = nome
        self.descricao = descricao
        self.preco = preco
        self.quantidade_estoque = quantidade_estoque
        self.id_categoria = id_categoria
        self.id_fornecedor = id_fornecedor

    def __repr__(self):
        return f"<Produto: {self.nome} - {self.descricao} - R${self.preco:.2f} - Estoque: {self.quantidade_estoque}>"

app/__init__.py
import os
from flask import Flask
from flask_migrate import Migrate
from config import db
from .routes.produto import bp_produto
from .routes.categoria import bp_categoria
from .routes.fornecedores import bp_fornecedores
from .routes.home import bp_home

def create_app():
    app = Flask(__name__)

    app.config['SECRET KEY'] = os.getenv('SECRET_KEY')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    username = os.getenv('DB_USERNAME')
    password = os.getenv('DB_PASSWORD')
    host = os.getenv('DB_HOST')
    mydb = os.getenv('DB_DATABASE')

    conexao = f"mysql+pymysql://{username}:{password}@{host}/{mydb}"

    app.config['SQLALCHEMY_DATABASE_URI'] = conexao


    db.init_app(app)
    migrate = Migrate(app,db)
    migrate.init_app(app, db)

    with app.app_context():
        from app.models.Produto import Produto
        from app.models.MovimentacaoEstoque import MovEstoque
        from app.models.Categoria import Categoria
        from app.models.Fornecedor import Fornecedor
        db.create_all()

    app.register_blueprint(bp_produto, url_prefix="/produtos")
    app.register_blueprint(bp_categoria, url_prefix="/categorias")
    app.register_blueprint(bp_fornecedores, url_prefix="/fornecedores")
    app.register_blueprint(bp_home)

    return app

app/routes/categoria.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from app.models.Categoria import Categoria
from config import db

bp_categoria = Blueprint("categoria",__name__)

@bp_categoria.route("/")
def listar_categorias():
    categorias = Categoria.query.all()
    return render_template('categorias.html', categorias=categorias)

@bp_categoria.route("/create", methods=['GET','POST'])
def create():
    if request.method == 'GET':
        return render_template('criar_categoria.html')
    elif request.method == 'POST':
        
        nome = request.form['nome']
        descricao = request.form['descricao']
        
        categoria = Categoria(nome,descricao)

        db.session.add(categoria)
        db.session.commit()

        return redirect(url_for('categoria.listar_categorias'))
    
@bp_categoria.route("/update/<id>", methods=['GET','POST'])
def update(id):
    if request.method == 'GET':
        return render_template('editar_categoria.html')
    elif request.method == 'POST':

        return "categoria atualizada com sucesso"
    

@bp_categoria.route("/delete/<id>", methods=['POST'])
def delete(id):
    categoria = Categoria.query.filter_by(id)
    db.session.delete(categoria)
    db.session.commit()
    return "deletado com sucesso papae"

app/routes/fornecedores.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from app.models.Fornecedor import Fornecedor
from config import db

bp_fornecedores = Blueprint("fornecedores",__name__)

@bp_fornecedores.route("/")
def listar_fornecedores():
    fornecedores = Fornecedor.query.all()
    return render_template('fornecedores.html', fornecedores=fornecedores)

@bp_fornecedores.route("/create", methods=['GET','POST'])
def create():
    if request.method == 'GET':
        return render_template('criar_fornecedor.html')
    elif request.method == 'POST':
        nome = request.form['nome']
        contato = request.form['contato']
        endereco = request.form['endereco']


        fornecedor = Fornecedor(nome,contato,endereco)

        db.session.add(fornecedor)
        db.session.commit()

        return redirect(url_for('fornecedores.listar_fornecedores'))

app/routes/home.py
from flask import Blueprint, render_template

bp_home = Blueprint('home', __name__)

@bp_home.route("/")
def home():
    return render_template('home.html')

app/routes/produto.py
from flask import Blueprint, render_template, request, flash
from app.models.Produto import Produto
from app.models.Categoria import Categoria
from app.models.Fornecedor import Fornecedor
from config import db

bp_produto = Blueprint("produto",__name__)

@bp_produto.route("/")
def listar_produtos():
    produtos = Produto.query.all()
    return render_template('produtos.html', produtos=produtos)

@bp_produto.route("/create", methods=['GET','POST'])
def create():
    if request.method == 'GET':
        return render_template('criar_produto.html')
    elif request.method == 'POST':
        

        nome = request.form['nome']
        descricao = request.form['descricao']
        preco = request.form['preco']
        quantidade_estoque = request.form['quantidade_estoque']
        categoria = request.form['categoria']
        fornecedor = request.form['fornecedor']

        id_categoria = Categoria.query.filter_by(nome=categoria).first()
        id_fornecedor = Fornecedor.query.filter_by(nome=fornecedor).first()

        print(id_categoria)
        
        produto = Produto(nome,descricao,preco,quantidade_estoque, id_categoria.id, id_fornecedor.id)


        db.session.add(produto)
        db.session.commit()


        return "produto criado com sucesso"
    
@bp_produto.route("/update/<id>", methods=['GET','POST'])
def update(id):
    if request.method == 'GET':
        return render_template('editar_produto.html')
    elif request.method == 'POST':

        return "produto atualizado com sucesso"
    

@bp_produto.route("/delete/<id>", methods=['POST'])
def delete(id):
    produto = Produto.query.filter_by(id)
    db.session.delete(produto)
    db.session.commit()
    return "deletado com sucesso papae"

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mega Stock 🛅 |{%block title%} {%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Mega Stock 🛅 </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

    <div class="container">

        <div class="container">
            {% block conteudo %}

            {% endblock %}
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/categorias.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorias</title>
</head>
<body>
    <h1>Categorias</h1>
    {% for categoria in categorias %}
        <ul>
            <li>{{ categoria.nome }}</li>
        </ul>
    {% endfor %}
</body>
</html>

app/templates/criar_categoria.html
<!DOCTYPE html>
<head>
    <meta charset='UTF-8'/>
    <title>Criar Categoria</title>
</head>
<body>
    <h1> Criar nova categoria</h1>

    <form action="{{ url_for('categoria.create') }}" method="post"> 
        <label for="nome">Nome:</label>
        <input type="text" name="nome"/>

        <br/><br/>

        <label for="descricao">Descrição:</label> <br>
        <textarea name="descricao" rows="4" cols="50"></textarea>

        <input type="submit" value="Criar" />

    </form>


</body>
</html>

app/templates/criar_fornecedor.html
<html>
    <head>
        <title>Criar Fornecedor</title>
    </head>
    <body>
        <h1>Criar Fornecedor</h1>
        <form action="{{url_for('fornecedores.create')}}" method="post">
            <input type="text" name="nome" placeholder="Nome">
            <input type="text" name="contato" placeholder="Contato">
            <input type="text" name="endereco" placeholder="Endereço">
            <button type="submit">Criar</button>
        </form>
    </body>
</html>

app/templates/criar_produto.html
{%extends "base.html"%}

{%block title%}
    Criar produto
{%endblock%}

{%block conteudo%}
    <form action="{{ url_for('produto.create') }}" method="post" class="needs-validation" novalidate>
        <div class="mb-3">
            <label for="nome" class="form-label">Nome:</label>
            <input type="text" class="form-control border border-secondary" id="nome" name="nome" required/>
        </div>

        <div class="mb-3">
            <label for="descricao" class="form-label">Descrição:</label>
            <textarea class="form-control border border-secondary" id="descricao" name="descricao" rows="4" required></textarea>
        </div>

        <div class="mb-3">
            <label for="preco" class="form-label">Preço:</label>
            <input type="number" class="form-control border border-secondary" id="preco" name="preco" step="0.01" required/>
        </div>

        <div class="mb-3">
            <label for="quantidade_estoque" class="form-label">Quantidade no estoque:</label>
            <div class="d-flex gap-2 align-items-center">
                <input type="range" class="form-range" id="amountRange" min="0" max="200" value="0" oninput="this.form.amountInput.value=this.value"/>
                <input type="number" class="form-control border border-secondary" style="width: 100px" id="amountInput" name="quantidade_estoque" min="0" max="200" value="0" oninput="this.form.amountRange.value=this.value"/>
            </div>
        </div>

        <div class="mb-3">
            <label for="categoria" class="form-label">Categoria:</label>
            <select class="form-select border border-secondary" id="categoria" name="categoria" required>
                <option value="eletrônicos">eletroniko 1</option>
                <option>categoria 2</option>
                <option>categoria 3</option>
            </select>
            <div class="mt-2">
                <a href="#" class="btn btn-outline-primary btn-sm">Adicionar nova categoria</a>
            </div>
        </div>

        <div class="mb-3">
            <label for="fornecedor" class="form-label">Fornecedor:</label>
            <select class="form-select border border-secondary" id="fornecedor" name="fornecedor" required>
                <option value="bokus">bokus 1</option>
                <option>fornecedor 2</option>
                <option>fornecedor 3</option>
            </select>
            <div class="mt-2">
                <a href="#" class="btn btn-outline-primary btn-sm">Adicionar novo fornecedor</a>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Criar</button>
    </form>
{%endblock%}

app/templates/fornecedores.html
<!DOCTYPE html>
<html>
    <head>
        <title>Fornecedores</title>
    </head>
    <body>
        <h1>Fornecedores</h1>
        <ul>
            {% for fornecedor in fornecedores %}
                <li>{{ fornecedor.nome }}</li>
            {% endfor %}
        </ul>
    </body>
</html> 

app/templates/home.html
 {% extends "base.html" %}

{% block title %}
    Home
{% endblock %}

{% block conteudo %}

{% endblock %}

app/templates/produtos.html
<!DOCTYPE html>
<html>
    <head>
        <title>Produtos</title>
    </head>
    <body>
        <h1>Produtos</h1>
        <ul>
            {% for produto in produtos %}
                <li>{{ produto.nome }}</li>
            {% endfor %}
        </ul>
    </body>
</html> 